### ISSUE TITLE
[Bug report] 从外部拖拽节点进来的时候， 节点可能会出现"粘连"在鼠标上，当拖拽完成，再次点击后报错Cannot read properties of undefined (reading 'model'

### ISSUE THREAD

**Issue by L2421800049** [didi/LogicFlow#1188]
## 问题描述

请用简洁的语言描述你遇到的 bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件，如何复现
从外部拖拽进lf的时候，可能会"粘连"到鼠标上，当拖拽完成，再次点击后报错Cannot read properties of undefined (reading 'model'

粘连是指，无需左键紧紧按住，他会跟随鼠标运动，当在鼠标再次点击这个节点的时候就报错了
3. 期望的表现
期望正常的拖追进来’
. 实际的表现
报错
![2708775e4867ee8a9334fd85053cf07](https://github.com/didi/LogicFlow/assets/57925981/a4cb1024-030d-492b-991f-8751c242b6a8)

Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'model')
TypeError: Cannot read properties of undefined (reading 'model')
    at eval (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:253509)
    at Array.reduce (<anonymous>)
    at t.value (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:253467)
    at Ot (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:6718)
    at t.n (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:6614)
    at t.eval (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:381624)
    at eval (webpack-internal:///./node_modules/@logicflow/core/dist/logic-flow.js:15:236805)

不好复现，随机出现

## 相关信息 context

LogicFlow Version:   
+-- @babel/core@7.22.1
+-- @logicflow/core@1.2.8
+-- @logicflow/extension@1.2.8
+-- @vue/babel-helper-vue-jsx-merge-props@1.4.0
+-- @vue/cli-plugin-babel@5.0.8
+-- @vue/cli-plugin-router@5.0.8
+-- @vue/cli-plugin-unit-jest@5.0.8
+-- @vue/cli-plugin-vuex@5.0.8
+-- @vue/cli-service@5.0.8
+-- ant-design-vue@1.7.8
+-- babel-plugin-import@1.13.6
+-- babel-plugin-transform-remove-console@6.9.4
+-- git-revision-webpack-plugin@3.0.6
+-- lodash.pick@4.4.0
+-- path@0.12.7
+-- v-drag@3.0.9
+-- vue-json-pretty@1.9.4
+-- vue-router@3.5.3
+-- vue@2.7.14
+-- vuex@3.6.2
+-- webpack-theme-color-replacer@1.4.7
+-- webpack@5.85.1
`-- yarn@1.22.19

Node Version:
v16.20.0
Platform:
windows

**Comment by towersxu** [comment]
可以参考这个https://github.com/didi/LogicFlow/issues/185
