### ISSUE TITLE
报错，在setMenuConfig找不到set

### ISSUE THREAD

**Issue by lydAndtry** [didi/LogicFlow#1360]
异常信息如下：
TypeError: Cannot read properties of undefined (reading 'set')
    at ./node_modules/@logicflow/extension/es/components/menu/index.js.Menu.setMenuConfig (index.js:328:1)
    at VueComponent.init (index.vue:279:1)
    at VueComponent.mounted (index.vue:221:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854:1)
    at callHook (vue.runtime.esm.js:4213:1)
    at insert (vue.runtime.esm.js:3139:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854:1)
    at Object.invoker [as insert] (vue.runtime.esm.js:2175:1)
    at invokeInsertHook (vue.runtime.esm.js:6340:1)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6559:1)
定位到写的那段代码：
lf.extension.menu.setMenuConfig({
        nodeMenu: false
      })

**Comment by lydAndtry** [comment]
已解决，版本错误

**Comment by gmqiyue** [comment]
是更新到哪个版本没有报错的？目前本地1.2.15版本会报错

**Comment by Ari1c** [comment]
我本地1.2.27 版本也会报错，静默模式下在 instance.value.extension.menu.setMenuConfig({...}) 就会有这个报错
