### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by ILikeStudyOops** [didi/LogicFlow#1684]
### 发生了什么？

代码直到今天早上都没有问题，在一次浏览器刷新后忽然出现了下面的问题，之后还原代码、重新安装依赖、更新最新版本都无法解决这个问题：
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'anchors')
TypeError: Cannot read properties of undefined (reading 'anchors')
    at getAnchors (webpack-internal:///./node_modules/@logicflow/core/es/util/node.js:46:22)
    at BaseEdgeModel.getBeginAnchor (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/BaseEdgeModel.js:253:74)
    at BaseEdgeModel.setAnchors (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/BaseEdgeModel.js:507:25)
    at executeAction (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:981:15)
    at PolylineEdgeModel.setAnchors (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:966:12)
    at BaseEdgeModel.initEdgeData (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/BaseEdgeModel.js:106:10)
    at PolylineEdgeModel.initEdgeData (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/PolylineEdgeModel.js:96:35)
    at PolylineEdgeModel.BaseEdgeModel (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/BaseEdgeModel.js:74:10)
    at new PolylineEdgeModel (webpack-internal:///./node_modules/@logicflow/core/es/model/edge/PolylineEdgeModel.js:89:24)
    at eval (webpack-internal:///./node_modules/@logicflow/core/es/model/GraphModel.js:395:16)
<img width="787" alt="Snipaste_2024-07-15_11-18-20" src="https://github.com/user-attachments/assets/954b0bb3-7fbb-4179-bc37-a61c01961bb4">

### logicflow/core版本

2.0.0-beta.3

### logicflow/extension版本

2.0.0-beta.3

### 浏览器&环境

Chrome

**Comment by boyongjiong** [comment]
描述无法定位问题，如有需要，请提供稳定可复现 demo
